#!/bin/bash

sudo iconsur set "/Users/kodydeda/Applications/Brave Browser Apps.localized/JIRA.app/"
sudo iconsur set "/Users/kodydeda/Applications/Brave Browser Apps.localized/YouTube.app/"

sudo iconsur cache
