#!/bin/bash

# Check if an argument is passed
if [ -z "$1" ]; then
    echo "Usage: sss <true|false>"
    exit 1
fi

# Check if the argument is 'true' or 'false'
if [ "$1" == "true" ]; then
    defaults write com.apple.screencapture disable-shadow -bool false
    echo "SystemScreenShots - Enabled"
elif [ "$1" == "false" ]; then
    defaults write com.apple.screencapture disable-shadow -bool true
    echo "SystemScreenShots - Disabled"
else
    echo "Invalid argument. Use 'true' or 'false'."
    exit 1
fi

